FROM python:3.11-slim

WORKDIR /workspace

COPY requirements-frontend.txt .
RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY .streamlit ./.streamlit
COPY frontend.py .

EXPOSE 8501
CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]